### ISSUE TITLE
Revoir l'administration pour l'utilisation de ico

### ISSUE THREAD

**Issue by gtraxx** [magix-cms/advantage#3]
Actuellement, l'administration utilise deux librairies (fonts) mais nous avons retiré celle-ci pour laisser place a "ico" via icomoon.
Il faut modifier l'administration pour simplement indiquer le nom de l'icône.

**Comment by Xarksass** [comment]
C'est mieux d'ajouter comme option de librairie, en plus de fontawesome et material-icons, la librairie icofont.
Même fonctionnement que fontawesome, indiquer la classe complète pour l'icône. Sur base de la structure suivante :
_nom_librairie_ ico ico-_nom_icone_
Exemple :
`material-icons ico ico-star`
Ça serait peut être bien aussi de retirer la prévisualisation de l'icône, ça a tendance à bugguer.

**Comment by Xarksass** [comment]
Finalement le mieux comme option sera donc :
custom => classe complète de l'icône (selon le gestionnaire d'icône utilisé)
